import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    padding: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  loadingText: {
    fontSize: 18,
    color: '#666666',
    fontFamily: 'GothamMedium',
    marginTop: 10,
    letterSpacing: 0.5,
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
  },
  scoreCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#FFF8F5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#E18731',
    shadowColor: '#E18731',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  scorePercentage: {
    fontSize: 36,
    fontFamily: 'GothamBold',
    color: '#E18731',
    letterSpacing: 0.5,
  },
  scoreMessage: {
    fontSize: 24,
    fontFamily: 'GothamBold',
    color: '#333333',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  levelCompleted: {
    fontSize: 16,
    fontFamily: 'GothamMedium',
    color: '#666666',
    letterSpacing: 0.5,
  },
  resultsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  statCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 15,
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 5,
    borderWidth: 2,
    borderColor: '#F0F0F0',
    shadowColor: '#E18731',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  statNumber: {
    fontSize: 24,
    fontFamily: 'GothamBold',
    color: '#E18731',
    marginBottom: 5,
    letterSpacing: 0.5,
  },
  statLabel: {
    fontSize: 14,
    fontFamily: 'GothamMedium',
    color: '#333333',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  statSubLabel: {
    fontSize: 12,
    fontFamily: 'GothamBook',
    color: '#666666',
    marginTop: 2,
  },
  rankCard: {
    backgroundColor: '#FFF8F5',
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#E18731',
    shadowColor: '#E18731',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  rankTitle: {
    fontSize: 18,
    fontFamily: 'GothamBold',
    color: '#333333',
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  rankImproved: {
    fontSize: 16,
    fontFamily: 'GothamMedium',
    color: '#27AE60',
    letterSpacing: 0.5,
  },
  rankMaintained: {
    fontSize: 16,
    fontFamily: 'GothamMedium',
    color: '#666666',
    letterSpacing: 0.5,
  },
  performanceCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 20,
    marginBottom: 30,
    borderWidth: 2,
    borderColor: '#F0F0F0',
    shadowColor: '#E18731',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  performanceTitle: {
    fontSize: 18,
    fontFamily: 'GothamBold',
    color: '#333333',
    marginBottom: 15,
    letterSpacing: 0.5,
  },
  performanceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  performanceLabel: {
    fontSize: 16,
    fontFamily: 'GothamMedium',
    color: '#666666',
    letterSpacing: 0.5,
  },
  performanceValue: {
    fontSize: 16,
    fontFamily: 'GothamBold',
    color: '#333333',
    letterSpacing: 0.5,
  },
  buttonContainer: {
    gap: 15,
  },
  primaryButton: {
    backgroundColor: '#E18731',
    paddingVertical: 15,
    borderRadius: 25,
    shadowColor: '#E18731',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: 'GothamBold',
    textAlign: 'center',
    letterSpacing: 1,
  },
  secondaryButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#E18731',
    shadowColor: '#E18731',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  secondaryButtonText: {
    color: '#E18731',
    fontSize: 16,
    fontFamily: 'GothamBold',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  tertiaryButton: {
    backgroundColor: 'transparent',
    paddingVertical: 10,
  },
  tertiaryButtonText: {
    color: '#666666',
    fontSize: 16,
    fontFamily: 'GothamMedium',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
});